### ISSUE TITLE
这个控件如何改成ui有3条，数据动态适配的？

### ISSUE THREAD

**Issue by wkboys** [hudafei1225/Android-DragAutoCardView#1]
ui有三个卡片的时候 myAdapter的数据是4条，当数据只有3条的时候差一条数据，当数据5条的时候少显示一条数据，请问大神如何适配一下？

**Comment by hudafei1225** [comment]
if (model.adverts.size() == 2) {
mCardStack.setVisibleCardNum(3);
} else if (model.adverts.size() > 2) {
mCardStack.setVisibleCardNum(4);
}
if (model.adverts.size() > 1) {
mCardStack.setEnableLoop(true);
mCardStack.reset(true);
mCardStack.startTimer();
}
我们默认是最多显示三张图片，一张图片的时候是不动的，setVisibleCardNum()这个值设置的显示数量是size-1，比方你设置了4，那么就只会显示3张，以此类推
